### ISSUE TITLE
Can't get Aspen to compile

### ISSUE THREAD

**Issue by VenkiPhy6** [thepeergroup/aspen#13]
Hi 

First off, sorry if this is a simple issue I can't solve because I am a Ruby noob! I just picked it up today morning. 

### Main Issue:
I am trying to make Aspen work in Windows 10. I followed all your installation instructions in your README.md. Then I tried to compile a `.aspen` and did this:

```
> cd D:\Misc_Projects\aspen #This is where I have the aspen directory which I got by forking and cloning
> bundle exec ./bin/aspen compile ./Example/example.aspen 
```
in Powershell. This is what I got:
```
bundler: command not found: ./bin/aspen
Install missing gem executables with `bundle install`
```

### My attempts at a solve:
I did do a `bundle install` before running this command (as mentioned in the instructions). Anyways I tried it again, but it didn't help. In fact, I checked it with:
```
> bundle info aspen
```
and it did correctly show:
```
  * aspen (0.1.0)
        Summary: Aspen turns simple text into graph data, compiling it into Cypher for Neo4j graph databases.
        Homepage: https://github.com/beechnut/aspen
        Path: D:/Misc_Projects/aspen
```
(I am assuming this means `bundle install` worked properly)

Then I read the `./bin/aspen` file and saw the shebang and it looks like it is trying to execute some command with the ruby interpreter. Since Windows doesn't understand the shebang I did this instead of the command in the instructions:

```
> bundle exec ruby ./bin/aspen compile ./Example/example.aspen
```

That gave me a "better" error (or is it?):
```
Traceback (most recent call last):
        11: from ./bin/aspen:3:in `<main>'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dry-cli-0.6.0/lib/dry/cli.rb:67:in `call'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dry-cli-0.6.0/lib/dry/cli.rb:114:in `perform_registry'
         8: from D:/Misc_Projects/aspen/lib/aspen/cli.rb:42:in `call'
         7: from D:/Misc_Projects/aspen/lib/aspen.rb:27:in `compile_text'
         6: from D:/Misc_Projects/aspen/lib/aspen.rb:27:in `new'
         5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/dry-container-0.7.2/lib/dry/container/mixin.rb:61:in `initialize'
         4: from D:/Misc_Projects/aspen/lib/aspen/configuration.rb:14:in `initialize'
         3: from D:/Misc_Projects/aspen/lib/aspen/configuration.rb:52:in `tag_lines'
         2: from D:/Misc_Projects/aspen/lib/aspen/configuration.rb:52:in `each'
         1: from D:/Misc_Projects/aspen/lib/aspen/configuration.rb:52:in `block in tag_lines'
D:/Misc_Projects/aspen/lib/aspen/configuration.rb:85:in `tag_line': There's no configuration option that matches the line: (Aspen::ConfigurationError)

  (Matt) [is friends with] (Brianna).


Maybe it's a spelling error?
```
(The `(Matt) [is friends with] (Brianna)` line comes from `example.aspen`. See below.) I don't know what to do next. 

### Some config info:
This is the ruby version I have installed:

```
> ruby --version
ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]
```

If there is any more Ruby configuration information needed from my end, let me know. (You may have to tell me the commands to get that info too since, again, I am a Ruby noob!)

### What is in `example.aspen`:
I don't think there is anything wrong with the `example.aspen` file. It is in my aspen directory in a folder called `Example`. `example.aspen` looks like this:
```
default Person, name
default_attribute Employer, company_name
reciprocal knows, is friends with

(Matt) [is friends with] (Brianna).
(Eliza) [knows] (Brianna).
(Matt) [is friends with] (Eliza).

(Matt) [works for] (Employer, UMass Boston).
```
which is basically the first example code on [Aspen website](https://aspen-lang.org/).

**Comment by VenkiPhy6** [comment]
I tried the same thing in a VM running Debian buster and had the same issue! So I don't think it is a Windows problem. 
```
venki@debian-docker-host:~/aspen$ bundle exec bin/aspen compile Example/example.aspen 
bundler: failed to load command: bin/aspen (bin/aspen)
Aspen::ConfigurationError: There's no configuration option that matches the line:

  # Write out the narrative data


Maybe it's a spelling error?


  /home/venki/aspen/lib/aspen/configuration.rb:85:in `tag_line'
  /home/venki/aspen/lib/aspen/configuration.rb:52:in `block in tag_lines'
  /home/venki/aspen/lib/aspen/configuration.rb:52:in `each'
  /home/venki/aspen/lib/aspen/configuration.rb:52:in `tag_lines'
  /home/venki/aspen/lib/aspen/configuration.rb:14:in `initialize'
  /home/venki/.rvm/gems/ruby-2.6.5/gems/dry-container-0.7.2/lib/dry/container/mixin.rb:61:in `initialize'
  /home/venki/aspen/lib/aspen.rb:27:in `new'
  /home/venki/aspen/lib/aspen.rb:27:in `compile_text'
  /home/venki/aspen/lib/aspen/cli.rb:42:in `call'
  /home/venki/.rvm/gems/ruby-2.6.5/gems/dry-cli-0.6.0/lib/dry/cli.rb:114:in `perform_registry'
  /home/venki/.rvm/gems/ruby-2.6.5/gems/dry-cli-0.6.0/lib/dry/cli.rb:67:in `call'
  bin/aspen:3:in `<top (required)>'
```
Ruby config in Debian buster.
```
venki@debian-docker-host:~/aspen$ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
```

**Comment by beechnut** [comment]
Hi @VenkiPhy6, it looks like you're right that this isn't an OS error at this point.

There are two things going on.

1. The code on the website is a bit out of date, and I need to update the examples so they're copy-and-pasteable.
2. There are comments in some of the examples, but Aspen doesn't actually support comments yet. (Really early days here.)

So, in the meantime, you can do two things.

1. Between the discourse (the lines with `default`, `reciprocal`, etc.) and the narrative (describing the things/people/relationships), put a line with four dashes: `----`.

```
...
reciprocal knows, is friends with
----
(Matt) [knows] (Brianna).
```

2. Delete any comments (lines beginning with `#`).

Let me know if that clears it up and lets it compile. Thanks for catching these things, definitely want parity between the language and documentation!

**Comment by beechnut** [comment]
Closing since this has been inactive for about 18 months
