### ISSUE TITLE
aspen as dsl for a rails app?

### ISSUE THREAD

**Issue by linojon** [thepeergroup/aspen#19]
hi , i'm investigating using neo4j and activegraph (neo4jrb) in a rails app. I'd be interested in using aspen to seed my database and for test fixtures. Would it take much to adapt this project to conform to the ActiveGraph data? (id's specifically i think)

**Comment by beechnut** [comment]
Hi @linojon, this is an interesting idea! I honestly don't know much about ActiveGraph at the moment. Could you provide a short example of the Aspen code you'd like to write and what you'd want the resulting output to be?

**Comment by beechnut** [comment]
Closing since it's been over a year. Feel free to re-open if needed!
