### ISSUE TITLE
Simplify installation

### ISSUE THREAD

**Issue by beechnut** [thepeergroup/aspen#2]
Frankly, I'm not sure how to design this gem so its executable gets put in the global `$PATH`, or without needing specific versions of Ruby. The goal is to have them download something and then from the command line, be able to, without `bundle exec` or `bin/aspen`, just write:

```
$ aspen some-command
```

What can we do to dramatically simplify installation and usage?

**Comment by beechnut** [comment]
It looks like using something like [ruby-packer](https://github.com/pmq20/ruby-packer) could package everything up nicely. Then they'd just need to download, and then use the command like above.

I'm also thinking it makes sense to enable installation over Homebrew, specifically taps. This isn't used enough to be part of homebrew-core yet.

**Comment by beechnut** [comment]
I'm finding that rubyc (ruby-packer) isn't working as expected: opened https://github.com/pmq20/ruby-packer/issues/123

**Comment by ihssanehatim** [comment]
Hello, I think building a web based application will simplify all these, having a UI where users can enter their inputs directly and get as a result the generated cypher file. I'm looking to contribute on this solution.

**Comment by beechnut** [comment]
Now installable via Rubygems—`gem install aspen-cli`.
